### ISSUE TITLE
Documentation does not list what the actual executables are

### ISSUE THREAD

**Issue by markaudacity** [desrod/pilot-link#17]
Difficult to actually use these tools when we _don't know what the actual commands are_ and `man pilot-link` doesn't return anything.
Pretty glaring oversight, y'all.

**Comment by desrod** [comment]
Yes, `man pilot-link` actually does work and lists the executables and what they do. I wrote that XML myself, so I'm confident it still works. In fact, I just built a clean copy of pilot-link on Ubuntu 24.04 (untested on a physical Palm OS device at this point), and after a few small changes to the xsltproc processor, it properly produced the manpages I expected: 

`TARGET DEVICE
       The /dev/pilot fallback has been removed in v0.12. The environment variable $PILOTPORT can be set  in  your  shell,  to
       save  specifying  the port each time. A serial device specified on the command-line will be used regardless of any $PI‐
       LOTPORT setting. If $PILOTPORT is not set, and -p is not supplied, all conduits in pilot-link will print the usage  in‐
       formation.  The  default connection rate is 9600 baud. You are welcome to try higher baud rates (19200, 38400, 57600 or
       higher) by setting the $PILOTRATE environment variable, but various machines  have  various  limitations.  (Be  careful
       about values higher than 115200 on older Linux boxes if you've been using setserial to change the multiplier).

CONDUITS
       A  complete list of conduits available from within the pilot-link package as of the date of this manpage. If you invoke
       any of the conduits from pilot-link with no command-line arguments at all, the usage summary will be printed.

       Note that there are widespread changes in this release - some conduits have been merged, a lot  have  had  new  options
       added and some options have been renamed or removed.

   addresses
       DEPRECATED: Use pilot-addresses --write|--human-readable instead.

   pilot-hinotes
       Syncronize your Hi-Notes database with your desktop machine.

   install-datebook
       installs a new datebook entry onto your Palm handheld.

   pilot-install-expenses
       Install an expense record from various parameters and arguments passed at connection time.

   install-hinote
       Install local files into your Hi-Note database on your Palm handheld.

   install-memo
       Installs a new Memo Pad entry onto your Palm handheld.

   pilot-install-netsync
       reads  or sets the Network Preferences information on a Palm Device. Modifies the "Network Preference" settings and re‐
       ports additional intormation about the Palm, such as the IP, hostname, and other information as they  are  set  on  the
       Palm.

   install-todo
       Updates the Palm ToDo list with one new entry.

   install-todos
       Updates the Palm ToDo list with entries from a local file.

   install-user
       Reads  or  sets a Palm User and UserID on a Palm Device. Modifies the "User Preference" settings and reports additional
       intormation about the Palm, such as the Username and UserID as they are set on the Palm`
