### ISSUE TITLE
Please enable the "GitHub Discussions" feature

### ISSUE THREAD

**Issue by unforgettableid** [desrod/pilot-link#4]
Dear @desrod and @juddmon:

The old pilot-unix mailing list seems to no longer exist.

Could you please enable the "GitHub Discussions" feature, which we could use for now instead?

It's quite easy to do.  If you wish to enable the feature, you simply:

* Go to https://github.com/desrod/pilot-link/settings.
* Scroll down.
* Click the green "Set up discussions" button.
* Scroll down again.
* Click the green "Start discussion" button.

Any thoughts?

Thank you for reading this!

**Comment by desrod** [comment]
On 3/13/22 12:08 AM, unforgettableid wrote:
> Could you please enable the "GitHub Discussions" feature, which we 
> could use for now instead?

The list has been dead for close to 10 years, nobody was really writing, 
so I archived it and the domain.

I've enabled the Discussions feature on GH, so let's be sure it's not 
going to be abused or misused.
